import { describe, it, expect } from 'vitest';
import { generateDailySummaryText } from '../../src/lib/dailySummaryReport';
import type { CashMovement, SaleTransaction, Shift } from '../../src/types';

// This report had no coverage at all while carrying its own copy of the drawer
// arithmetic — it totalled tx.total for every sale whose dominant method was
// cash, which counted a split sale's card half as drawer cash and ignored both
// the change handed back and any refund. It goes through summarizeShift now,
// the same function behind the Z-report, and these lock that down: the two
// documents describe one drawer and must not disagree about it.

const sale = (over: Partial<SaleTransaction>): SaleTransaction => ({
  id: 'TX',
  date: '2026-07-16T10:00:00.000Z',
  items: [],
  subtotal: 0,
  discount: 0,
  discountType: 'none',
  discountValue: 0,
  tax: 0,
  total: 0,
  paymentMethod: 'card',
  customerId: null,
  status: 'completed',
  ...over,
});

const movement = (over: Partial<CashMovement>): CashMovement => ({
  id: 'cm',
  shiftId: 'shift-1',
  type: 'pay_out',
  amount: 0,
  reason: 'test',
  performedBy: 'Ada',
  createdAt: '2026-07-16T10:00:00.000Z',
  ...over,
});

const shift: Shift = {
  id: 'shift-1',
  openedAt: '2026-07-16T08:00:00.000Z',
  openedBy: 'Ada',
  openingFloat: 100,
};

const report = (over: Partial<Parameters<typeof generateDailySummaryText>[0]> = {}) =>
  generateDailySummaryText({
    storeName: 'Test Store',
    currency: '$',
    date: '2026-07-16',
    transactions: [],
    shift,
    ...over,
  });

/** The figure printed on a named line, e.g. "Expected Cash in Drawer". */
const lineValue = (text: string, label: string): string =>
  text.split('\n').find((l) => l.includes(label)) ?? '';

describe('generateDailySummaryText drawer arithmetic', () => {
  it('counts a cash sale net of the change handed back', () => {
    // $40 sale, $50 tendered, $10 back: the drawer gained $40, not $50.
    const text = report({
      transactions: [sale({ paymentMethod: 'cash', total: 40, cashPaid: 50, cashChange: 10 })],
    });
    expect(lineValue(text, 'Cash Collected')).toContain('$40.00');
    expect(lineValue(text, 'Expected Cash in Drawer')).toContain('$140.00');
  });

  it('counts only the cash half of a split sale', () => {
    // The regression: dominant method is card here, but the old code keyed on
    // paymentMethod and would have counted the whole $100 as cash — or nothing.
    const text = report({
      transactions: [
        sale({
          paymentMethod: 'card',
          total: 100,
          payments: [
            { method: 'card', amount: 80 },
            { method: 'cash', amount: 20 },
          ],
          cashChange: 0,
        }),
      ],
    });
    expect(lineValue(text, 'Cash Collected')).toContain('$20.00');
    expect(lineValue(text, 'Expected Cash in Drawer')).toContain('$120.00');
  });

  it('takes a refund back out of the drawer', () => {
    const text = report({
      transactions: [
        sale({
          paymentMethod: 'cash',
          total: 60,
          cashPaid: 60,
          cashChange: 0,
          status: 'partial',
          refundedAmount: 30,
        }),
      ],
    });
    expect(lineValue(text, 'Expected Cash in Drawer')).toContain('$130.00');
  });

  it('moves the expected figure by petty cash in both directions', () => {
    const withPayOut = report({ cashMovements: [movement({ type: 'pay_out', amount: 25 })] });
    expect(lineValue(withPayOut, 'Expected Cash in Drawer')).toContain('$75.00');
    expect(withPayOut).toContain('Petty Cash Payouts');

    const withPayIn = report({ cashMovements: [movement({ type: 'pay_in', amount: 25 })] });
    expect(lineValue(withPayIn, 'Expected Cash in Drawer')).toContain('$125.00');
    expect(withPayIn).toContain('Cash Deposits');
  });

  it('reports the variance against the counted cash', () => {
    const text = report({
      shift: { ...shift, countedCash: 90 },
      transactions: [],
    });
    expect(lineValue(text, 'Counted Cash')).toContain('$90.00');
    // A shortfall reads "-$10.00". The sign used to land inside the symbol
    // ("$-10.00"), which on a forwarded report skims as a typo or as a surplus.
    expect(lineValue(text, 'Counted Cash')).toContain('-$10.00');
  });

  it('omits the counted line entirely on an open shift', () => {
    expect(report()).not.toContain('Counted Cash');
  });
});

describe('generateDailySummaryText content', () => {
  it('names the store rather than a hard-coded product name', () => {
    // The footer used to read "Generated by Antigravity POS" on every terminal.
    const text = report({ storeName: 'Corner Cafe' });
    expect(text).toContain('CORNER CAFE');
    expect(text).toContain('Generated by Corner Cafe');
  });

  it('ranks the best sellers by units, longest first', () => {
    const line = (name: string, quantity: number) => ({
      productId: name,
      productName: name,
      price: 1,
      cost: 0,
      quantity,
      total: quantity,
    });
    const text = report({
      transactions: [
        sale({ total: 3, items: [line('Latte', 1), line('Bun', 3)] }),
        sale({ total: 2, items: [line('Latte', 2)] }),
      ],
    });
    const top = text.slice(text.indexOf('TOP SELLING ITEMS'));
    expect(top).toContain('1. Latte (3 sold)');
    expect(top).toContain('2. Bun (3 sold)');
  });

  it('leaves out the optional lines when there is nothing to report', () => {
    const text = report();
    expect(text).not.toContain('Discounts:');
    expect(text).not.toContain('TOP SELLING ITEMS');
  });

  it('survives having no shift at all', () => {
    const text = report({ shift: null });
    expect(lineValue(text, 'Opening Float')).toContain('$0.00');
  });
});
